services:
  l2j-login-server:
    image: nonom/l2j-server-login:latest
    ports:
      - 2106:2106
    depends_on:
      l2j-database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - L2JLOGIN_DB_INIT=${DB_INIT:-0}
      - L2JLOGIN_DB_HOST=l2j-database
      - L2JLOGIN_DB_PORT=3306
      - L2JLOGIN_DB_NAME=l2jls
      - L2JLOGIN_DB_USER=${DB_USER}
      - L2JLOGIN_DB_PASS=${DB_PASS}
      - L2JLOGIN_DB_INSTALL_USER=root
      - L2JLOGIN_DB_INSTALL_PASS=${MARIADB_ROOT_PASSWORD}
      - L2JLOGIN_server_GameServerHost=*
      - L2JLOGIN_database_URL=jdbc:mariadb://l2j-database:3306/l2jls
      - L2JLOGIN_database_User=${DB_USER}
      - L2JLOGIN_database_Password=${DB_PASS}

  l2j-game-server:
    image: nonom/l2j-server-game:latest
    ports:
      - 7777:7777
    depends_on:
      l2j-database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - L2JGAME_DB_INIT=${DB_INIT:-0}
      - L2JGAME_DB_HOST=l2j-database
      - L2JGAME_DB_PORT=3306
      - L2JGAME_DB_NAME=l2jgs
      - L2JGAME_DB_USER=${DB_USER}
      - L2JGAME_DB_PASS=${DB_PASS}
      - L2JGAME_DB_INSTALL_USER=root
      - L2JGAME_DB_INSTALL_PASS=${MARIADB_ROOT_PASSWORD}
      - L2JGAME_server_LoginHost=l2j-login-server
      - L2JGAME_server_LoginPort=9014
      - L2JGAME_database_URL=jdbc:mariadb://l2j-database:3306/l2jgs
      - L2JGAME_database_User=${DB_USER}
      - L2JGAME_database_Password=${DB_PASS}

  l2j-database:
    image: mariadb:11.8
    volumes:
      - l2j-database-data:/var/lib/mysql:rw
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_HOST=%
      - MARIADB_MYSQL_LOCALHOST_USER=1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  l2j-database-data:
